services:
  mariadb:
    image: mariadb:11
    container_name: insvnter-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: insvnter_ai
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: insvnter-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7
    container_name: insvnter-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mariadb_data:
  redis_data:
  mongo_data:
